#!/bin/bash -e
name=$1

if [[ $name = "" ]]; then
  echo "Name not specified, using `basename $(pwd)`"
  name=`basename $(pwd)`
fi

echo ">>> Building for Linux..."
stack docker pull
stack build --docker
rm -rf .stack-fpm
mkdir -p .stack-fpm/usr/local
cp -r `stack path --docker --local-install-root` ./.stack-fpm/usr/local/
version=`cat package.yaml | ggrep -Po "version: '(\K[^']*)"`
cd .stack-fpm
echo ">>> Building Linux packages..."
tar -zcvf .stack-fpm.tar.gz *
fpm -t deb -s tar --deb-pre-depends libgmp-dev -n $name -v $version ./.stack-fpm.tar.gz
fpm -t rpm -s tar --rpm-os linux --rpm-autoreq -n $name -v $version ./.stack-fpm.tar.gz
mkdir -p ../dist
mv ./*.deb ../dist/
mv ./*.rpm ../dist/
cd ..
rm -rf .stack-fpm

if [ `uname` = "Darwin" ]; then
  echo ">>> Building Darwin..."
  stack build
  rm -rf .stack-fpm
  mkdir -p .stack-fpm/usr/local
  cp -r `stack path --local-install-root` ./.stack-fpm/usr/local/
  version=`cat package.yaml | ggrep -Po "version: '(\K[^']*)"`
  cd .stack-fpm
  echo ">>> Building Darwin packages..."
  tar -zcvf .stack-fpm.tar.gz *
  fpm -t osxpkg -s tar -n $name -v $version ./.stack-fpm.tar.gz
  mkdir -p ../dist
  mv ./*.pkg ../dist/
fi

cd ..
rm -rf .stack-fpm
