#!/bin/bash -e
name=$1

if [[ $name = "" ]]; then
  echo "Name not specified, using `basename $(pwd)`"
  name=`basename $(pwd)`
fi

echo ">>> Building linux binaries..."
stack docker pull
stack build --docker
rm -rf .stack-fpm
mkdir -p .stack-fpm/usr/local/bin/
cp `stack path --docker --dist-dir`/build/$name/$name ./.stack-fpm/usr/local/bin/
version=`cat package.yaml | ggrep -Po "version: '(\K[^']*)"`
cd .stack-fpm
echo ">>> Building linux packages..."
tar -zcvf .stack-fpm.tar.gz *
fpm -t deb -s tar --deb-pre-depends libgmp-dev -n $name -v $version ./.stack-fpm.tar.gz
fpm -t rpm -s tar --rpm-os linux --rpm-autoreq -n $name -v $version ./.stack-fpm.tar.gz
mkdir -p ../dist
mv ./*.deb ../dist/
mv ./*.rpm ../dist/
cd ..
rm -rf .stack-fpm

if [ `uname -n` = "Darwin" ]; then
  echo ">>> Building darwin binaries..."
  stack build
  rm -rf .stack-fpm
  mkdir -p .stack-fpm/usr/local/bin/
  cp `stack path --dist-dir`/build/$name/$name ./.stack-fpm/usr/local/bin/
  echo ">>> Building darwin packages..."
  cd .stack-fpm
  tar -zcvf .stack-fpm.tar.gz *
  version=`cat package.yaml | ggrep -Po "version: '(\K[^']*)"`
  fpm -t osxpkg -s tar -n $name -v $version ./.stack-fpm.tar.gz
  mkdir -p ../dist
  mv ./.*.pkg ../dist/
fi

cd ..
rm -rf .stack-fpm
